### ISSUE TITLE
Deprecation notice for authentication via URL query parameters

### ISSUE THREAD

**Issue by andrewroberts** [leonhartX/gas-github#119]
Just had this message from GitHub. Could it have been generated by the GitHub assistant (I don't access GitHub any way that I can think of)?

"_On February 3rd, 2020 at 23:11 (UTC) your personal access token (gas-github_xxxxxxxxx) using Mozilla/5.0 (X11; CrOS x86_64 12499.66.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.106 Safari/537.36 was used as part of a query parameter to access an endpoint through the GitHub API:_

_https://api.github.com/repositories/190063763/branches/v1.9_

_Please use the Authorization HTTP header instead, as using the `access_token` query parameter is deprecated._

_Depending on your API usage, we'll be sending you this email reminder once every 3 days for each token and User-Agent used in API calls made on your behalf.
Just one URL that was accessed with a token and User-Agent combination will be listed in the email reminder, not all._

_Visit https://developer.github.com/changes/2019-11-05-deprecated-passwords-and-authorizations-api/#authenticating-using-query-parameters for more information._"

**Comment by odimko** [comment]
I'm getting the same issue: trying to pull any branch from a repo results into an error "Unable to update the file".
Also received an identical e-mail from Github.

**Comment by ddelange** [comment]
> _Please use the Authorization HTTP header instead_

It's weird, because it looks like the plugin is already doing that: https://github.com/leonhartX/gas-github/blob/v4.0.3/src/scm/github.js#L33-L35

ref for best practices: https://developer.github.com/v3/auth/#basic-authentication

**Comment by leonhartX** [comment]
Thanks, will look into this, actually some request is passing the token as query parameter

**Comment by leonhartX** [comment]
4.0.7 released, moved all access token to Authorization header

**Comment by odimko** [comment]
@leonhartX thanks a lot! Works like a charm :1st_place_medal: 
One thing though, I have received an e-mail from GH again with a similar message:

_Hi @odimko,
On February 10th, 2020 at 11:43 (UTC) your personal access token (gas-github_xxxxxxxxxxxxxx) using Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.87 Safari/537.36 was used as part of a query parameter to access an endpoint through the GitHub API:
https://api.github.com/user
Please use the Authorization HTTP header instead, as using the `access_token` query parameter is deprecated and will be removed **July 1st, 2020**.
Depending on your API usage, we'll be sending you this email reminder once every 3 days for each token and User-Agent used in API calls made on your behalf.
Just one URL that was accessed with a token and User-Agent combination will be listed in the email reminder, not all.
Visit https://developer.github.com/changes/2019-11-05-deprecated-passwords-and-authorizations-api/#authenticating-using-query-parameters for more information.
Thanks,
The GitHub Team_

Any thought on this? Since you've mentioned that all access tokens are in the Authorization header, I wonder why I am getting this e-mail again.
Thanks in advance!

**Comment by leonhartX** [comment]
oh, actually missed one, for access the `https://api.github.com/user` to login, will fix this later
