### ISSUE TITLE
Add support for new IDE

### ISSUE THREAD

**Issue by andrewroberts** [leonhartX/gas-github#129]
With the imminent release of [the new IDE](https://mashe.hawksey.info/2020/07/first-look-at-the-new-google-apps-script-integrated-development-environment-ide-script-editor/#gref) can the extension be updated to work with it?

Particularly important as I can remember reading somewhere that we'll lose the option to use the existing one next year.

**Comment by leonhartX** [comment]
I'll take some time to look at the new IDE, but sadly I can't promise anything because this extension is totally build on many hacky things used in the previous IDE, one idea is to switch some internal RPC calls to the Google apps script API (which is the backend of clasp), but I don't know whether I can get enough time to do that.

**Comment by andrewroberts** [comment]
I've not worked on a chrome extension before, but if you were willing to provide a little hand-holding I'd be willing to help with the upgrade??

**Comment by RomainVialard** [comment]
Yes, it would be greatly appreciated!
@leonhartX do you have access to the new IDE or not yet?

**Comment by rielzzapps** [comment]
I am willing to help with it.

**Comment by leonhartX** [comment]
Thanks, I have a partial PR created years ago to try to use the GAS API, if someone would like to take a look it will be very appreciate 
#107 

if the API part is fine, then we just need to modify some UI part to match the CSS of the new IDE(though I haven't tried it yet)

**Comment by derekantrican** [comment]
Just to add here some more info on the new IDE: https://www.benlcollins.com/apps-script/google-apps-script-ide/ and that the new IDE looks like it will be rolling out to everyone in the next 2 weeks.

+1 would love to see this extension supported in the new editor!

**Comment by derekantrican** [comment]
I also logged a feature request on Google's side to add this support natively to the new IDE: https://issuetracker.google.com/issues/176124900 star it or comment on it if you want to raise awareness

**Comment by leonhartX** [comment]
hey guys, with #107 and #130, I think it can works with the new IDE now, the main changes are
- need to login google to use scripts API
- since it moves to scripts API, we can get rid of some known issues like error with same function name and filename
- add support to run in multi tabs

I'll take some more time to check and then publish it to the web store, but if someone wants to try it (and please help to find some bugs), please check out the code, and use `Load unpacked` in chrome extension settings to install it (need to remove the one installed from web store first)

**Comment by leonhartX** [comment]
submitted 5.0.0 to chrome web store, waiting for review now

**Comment by leonhartX** [comment]
5.0.0 released

**Comment by RomainVialard** [comment]
Thank you @leonhartX! And happy new year!

**Comment by andrewroberts** [comment]
Thank you! This is fantastic news - an essential piece of kit and one more reason I don't have to jump back to the legacy editor.

**Comment by leonhartX** [comment]
Sorry guys, I've noticed that since the OAuth app is still under review, google has a limitation to only allow 100 users give permission to the app, so you may see errors say it can not grant permission 🤦 
I don't want to rollback the released one so please wait until the review completed or install it from source code to use v4.0.3 with the legacy editor, sorry for the inconvenience 

![image](https://user-images.githubusercontent.com/3993518/103592458-75e98a80-4f36-11eb-95ff-cb768cada6b9.png)
