### ISSUE TITLE
Supporting .gitignore?

### ISSUE THREAD

**Issue by Duleepa** [leonhartX/gas-github#38]
We have a couple of .gs files that should not be commited (dev variables and the like). I've noticed that pushing to the repo will ignore the .gitignore rules. Is that an issue with the github api?

**Comment by leonhartX** [comment]
That's not an issue about github api. Just because gas do not support .gitignore files. So when push code, the extension has no idea about which file should be ignored.
Although we can pull .gitignore every time before push but it seems too much, since extension need to parse the content of .gitignore itself.(I will take some time to check this)
Also please notice that when push code, you can choose which code to push, hope this can be a work around for you.

**Comment by leonhartX** [comment]
v3.2.0 has added a regex ignore pattern, hope this will be helpful
