### ISSUE TITLE
gas-github not able to detect files in my script editor

### ISSUE THREAD

**Issue by edmiss** [leonhartX/gas-github#67]
backgroud:
I am using G suite service which is offered by my company. 

Recently whenever I push to my github repo, it deletes everything in the repo, mostly because gas-github does not detect anything in my gs editor. 

![capture2](https://user-images.githubusercontent.com/18342222/38157826-81dd6c36-343f-11e8-8de7-934daf41c394.PNG)

Leon, your add-on helped me so much in the past and it would be really painful to live without it lol.

Let me know if there is a solution for this.

**Comment by leonhartX** [comment]
@edmiss thanks for the report, recently I got some report about the extension is not working, maybe it's because the last change #63.

Can you check the response from chrome's develop tools about the request filtered by `ideService` ?

![screen shot 2018-04-02 at 10 38 12](https://user-images.githubusercontent.com/3993518/38179779-fb12ea94-3661-11e8-802b-bfcb727d4765.png)

**Comment by leonhartX** [comment]
And If you could, please try rollback to v3.3.2.
You can download the crx from [here](https://github.com/leonhartX/gas-github/releases/tag/V3.3.2) and install it manually.
If this works for you, then the root cause should be the last release.

**Comment by machinefriendly** [comment]
@leonhartX I have same issue, and you have below the screenshot with ideService filtered when I push to git: 
![image](https://user-images.githubusercontent.com/2982582/38242405-025244de-3735-11e8-8125-cc32edefb58e.png)
Edit gave "Everything is up-to-date", while on github repo new brunch I have only readme.md.
Thanks in advance.

**Comment by leonhartX** [comment]
@machinefriendly does your script contains function which is the same name as the filename?
See
https://github.com/leonhartX/gas-github#5known-issues

**Comment by machinefriendly** [comment]
@leonhartX no, just verified and there is no such function or file name.

**Comment by machinefriendly** [comment]
@leonhartX I find the cause of the problem, due to conflict with another scripts editor addon called "[AppsScript Color](https://chrome.google.com/webstore/detail/appsscript-color/ciggahcpieccaejjdpkllokejakhkome?hl=en-GB)", when I deactivate that addon, our Github addon works well as expected. I see AppsScriptColor addon has recently launched its big version 1.01 on 3/22, timing corresponds. Hope you guys could help figure out a solution. Thanks.

**Comment by leonhartX** [comment]
@machinefriendly thanks! I'll take some time to investigate this.

**Comment by edouardindemniflight** [comment]
Hello, 
Just to inform you that I get the same trouble. 
I desactivated appscript color and it's now work perfectly.

**Comment by leonhartX** [comment]
Thanks for the report, seems the appscript color has changed the html of files so I can not match them.
going to fix this and release a new version

**Comment by leonhartX** [comment]
v3.3.5 released, should fix this

**Comment by JeanRemiDelteil** [comment]
@leonhartX  I see that you fixed this issue !

It's strange because previously AppsScriptColor also allowed to have folder, I suppose that it's because now all files are moved to accommodate with the new Folder structure.

So is everything okay when using both extensions ? (You can check if appsscriptColor tempered with the files with the **.asc_FolderRoot** class. (Should be only one).

Did you check that it also works when files are inside a folder (when the file name contains a "/" character) ?

**Comment by leonhartX** [comment]
@JeanRemiDelteil sadly this not works with folder now.
I was expect the innerText of `div.item` to be the filename, but after enable Appscript Color, the path will be deleted from the innerText 😢

**Comment by JeanRemiDelteil** [comment]
@leonhartX  I added detailed info here: https://github.com/JeanRemiDelteil/appsScriptColor/issues/2

> Get the FULL file name from the attribute "title" of div.gwt-Label.piece.name inside div.project-items-list
This attribute is correctly update by the GAS editor UI, while the aria-label is not, and the text content will be updated to remove the folder-like part of the file name by AppsScriptColor.

**Comment by leonhartX** [comment]
v3.3.6 released, should work with AppsScript Color's folder.
