### ISSUE TITLE
Too many permissions in manifest.js

### ISSUE THREAD

**Issue by StAmourD** [leonhartX/gas-github#76]
I received this after the latest update:
![image](https://user-images.githubusercontent.com/3241173/38500133-828f0294-3bd7-11e8-8781-1d921cd1cca0.png)

@gulliveruk Could you remove this from the live version on the app store?

https://github.com/leonhartX/gas-github/blob/4496d9b0a4c5fa457ec26c0da363c323fb9a0ba2/manifest.json#L63

Thanks
David

**Comment by gulliverhan** [comment]
Hey - so I believe that these are required for gitlab self hosted - though I can look at restricting it down to just the api endpoints to see if that works

**Comment by leonhartX** [comment]
Actually I also think this maybe too ambitious. Personally I always be very careful when an extension ask for read data from all website.
Since we even haven't test the hosted gitlab, maybe it's better to just support gitlab.com (this is the reason why I just support bitbucket.org but not hosted bitbucket.)

Or we can check whether the other login ways(like oauth from web) which can avoid the cross-origin problem.
